@extends('layouts.master')

@section('content')
<section class="s-content s-content--narrow s-content--no-padding-bottom">
    <article class="row format-standard">

        <div class="s-content__header col-full">
        <h2 class="s-content__header-title">Capítulo 3</h2>
                <h1 class="s-content__header-title">{{ $current->title }}</h1>
        </div> <!-- end s-content__header -->

        <div class="col-full s-content__main">
            
            <p class="lead">La soledad es un estado que todos los seres humanos pueden experimentar y que, por su complejidad, tiene diferentes acepciones. En general se asocia con situaciones y emociones negativas, como la pérdida y la tristeza.</p>
            <p>Hay personas que pueden experimentarla con mayor facilidad y este es el caso de los adultos mayores quienes, por su edad avanzada, conviven constantemente con la partida y muerte de sus seres queridos.</p>
            <p>Para entender dicho estado en los adultos mayores, Germans Trias retoma la propuesta de Vicente Madoz, quien la define como el “convencimiento apesadumbrado de estar excluido, de no tener acceso a ese mundo de interacciones, siendo una condición de malestar emocional que surge cuando una persona se siente incomprendida o rechazada por otros o carece de compañía para las actividades deseadas, tanto físicas como intelectuales o para lograr intimidad emocional”.</p>
            <p>A pesar de ser una condición común, <strong>se vive y supera de diferentes maneras</strong>. Chávez Ortíz indica que es un tema sumamente amplio dada la subjetividad que encierra. En los adultos mayores, por ejemplo, hay quienes estando solos no se sienten así, pero también existen casos en los que a pesar de estar acompañados tienen una sensación de soledad. Es decir, “hay una soledad real y una soledad que no es real, visible cuando a pesar de estar con muchas personas sienten que su vida ya no tiene sentido”. La maestra también aclara que esto se relaciona con un proceso emocional y de aprendizaje, es decir, cómo las generaciones se han preparado para llegar a edades avanzadas.</p>
            <p>Dependiendo de la historia de cada adulto mayor, al experimentar soledad, actúan y viven de cierta manera. Sin embargo, es importante señalar que <strong>el bienestar debe prevalecer en cualquier situación.</strong></p>
            
            <h2>Corazón contento</h2>
            <p>Doña Inés es una mujer entregada, trabajadora, agradecida y feliz. Tuvo siete hermanos y vivió con sus padres hasta que pudo tener su propia casa. Ella recuerda con amor a las personas que le dieron la vida y a su hermana mayor, quien no estudió para ayudar con los gastos del hogar. </p>
            <p>Durante la entrevista telefónica, doña Inés rememora cálidamente cuando estudió la primaria y formó parte de la escolta, aunque tristemente cuenta que nunca pudo ser la abanderada. Años más tarde, decidió estudiar comercio en un Centro Escolar, aunque curiosamente su diploma la acreditaba como contadora particular lo que le permitió trabajar como secretaria por más de 30 años. </p>
            <p>Con los ingresos que fue obteniendo, poco a poco construyó su patrimonio. Primero compró un terreno, después, con la ayuda de un arquitecto, hizo los planos para construir su primera casa, la cual habitó aún estando en obra negra. Con el tiempo perfeccionó su hogar y pudo construir una serie de departamentos y locales que en la actualidad renta. </p>
            <p>Hoy en día doña Inés vive sola y de manera independiente gracias a su pensión y los ingresos de sus arrendamientos. El hogar unipersonal no es tan común en los adultos mayores mexicanos, así lo indican datos del <strong>Inapam</strong> “La mayor parte de la población adulta mayor mexicana, en específico el 88.1 por ciento, forma parte de un hogar familiar, el resto, 11.1 por ciento forman hogares unipersonales, los cuales enfrentan retos y limitaciones frente al deterioro inminente de la edad, resultando necesario la generación de redes sociales de apoyo”.</p>
            <p>A pesar de vivir sola, doña Inés se siente acompañada y apoyada por su familia. Su hijo Emiliano de 33 años viene de la Ciudad de México cada fin de semana. Su hermana Chelo, quien enviudó hace unos años, en ocasiones se queda con ella y aprovechan para hacer el quehacer, cocinar, ver la tele y platicar. Su sobrina Ángeles vive en uno de los departamentos que renta y siempre tiene atenciones con ella, además comen todos los días juntas. Recientemente, Guadalupe, otra de sus sobrinas, se ha unido a esta dinámica. “Cooperamos para hacer la comida y a veces cocinamos entre todas”. </p>
            <p>Esta sensación de compañía no sucede con las generaciones más jóvenes pues Inés comparte que los hijos de Ángeles sólo saludan y se despiden, pero no tienen la confianza de platicar más con ella, “No son nada atentos, no preguntan tía ¿está bien? ¿le falta algo? ¿le duele algo? [...] tal vez sea porque están adolescentes o porque así es su papá, eso se aprende”.</p>
            <p>En la vida de doña Inés hay altas y bajas, al igual que en los casos anteriores ella menciona que tiene aflicciones. Le preocupa que su hijo no tenga trabajo y que al visitarla ocupe todo el tiempo el celular y no le ayude en la casa. “Siento que no ha madurado, debería dejar el celular y platicar conmigo [...] agarrar la escoba, lavar trastes, algo”.</p>
            
            <!-- Fotografía doña Inés -->
            
            <h2>Te quiero pero me canso</h2>
            <p>Sobre los tipos de interacción con los adultos mayores, <strong>Ángel Manuel Brito Carranza, miembro integrante del colectivo</strong> <a href="https://www.facebook.com/AmatePsicogerontologos/">Amate, Psicogerontólogos educando para la vejez</a>, asegura que está íntimamente relacionada con las historias personales, porque determinan la visión que cada persona hace sobre esta etapa de la vida y moldea el acercamiento a la misma. </p>
            <p>Doña Inés dice que uno de los momentos más difíciles de su vejez ha sido el cuidado de su hermano Vicente, otro adulto mayor que tenía una discapacidad mental. Durante un tiempo Inés lo cuidó debido a su condición, sin embargo, la demanda de atención se hizo más complicada al entrar en una edad avanzada. Esta situación hizo que la relación se tensara provocando fricciones entre los hermanos. </p>
            <p>Al respecto los psicólogos <strong>Renato Zambrano Cruz y Patricia Ceballos Cardona</strong> lo explican en su artículo <a href="http://www.scielo.org.co/pdf/rcp/v36s1/v36s1a05.pdf">Síndrome de carga del cuidador</a></p>
            <p><blockquote>Luego de un daño cerebral [...] las personas quienes los padecen exhiben síntomas y características que indican deterioro en su capacidad de autocuidado y autonomía en general. Esto se debe a alteraciones cognitivas, motoras, en la capacidad lingüística o dificultades emocionales. Fuera de estas secuelas, los pacientes presentan, con frecuencia, sintomatología de orden psiquiátrico [...]. Por esto, es necesario que otras personas <strong>realicen o ayuden a efectuar las funciones</strong> en las que el paciente con daño cerebral ya no se puede desempeñar, además de brindar <strong>apoyo emocional</strong>, necesario para la adaptación del paciente a la nueva situación. Estas personas reciben el nombre de cuidadores y normalmente existen dos grupos: [...] <strong>cuidadores familiares, y cuidadores profesionales</strong>. Tanto unos como otros manifiestan dificultades, malestar físico y mental, incluso trastornos mentales, que tienen estrecha relación con su actividad como cuidadores. Es de especial atención el <strong>primer grupo</strong>, pues se considera que disponen de <strong>menos estrategias de afrontamiento ante estas dificultades</strong>. La serie de dificultades está caracterizada principalmente por sentimientos de carga, estrés y tristeza, y se les ha denominado síndrome de carga del cuidador.</blockquote></p>
            <p class="lead">El cuidado de una persona puede ser complicado, en especial si no se tienen los medios necesarios para facilitar dicha labor. Por ello, la terapista ocupacional Silvia Delgado Morales explica que el tratamiento con especialistas tiene muchos beneficios, porque en primera instancia son ellos quienes pueden determinar un buen diagnóstico, canalizar, proporcionar soluciones y dar un buen tratamiento. Este, afirma la especialista, es el primer paso para generar una buena calidad de vida porque de esto dependerá el bienestar de la persona con deterioro.</p>
            <p>Doña Inés recuerda que lo más difícil era cambiar a Vicente, porque sola no se lo aguantaba. Comenta que a pesar de que fueron meses difíciles, extraña a su hermano y que tiene buenos recuerdos de él. </p>
            <p>Ella comparte que su tranquilidad está en el bienestar de los que ama. Quiere que su hijo tenga un buen trabajo, que sus sobrinos estudien una licenciatura y superen los logros de sus padres. </p>
            <p>Procura estar activa, por eso va a la Casa del Abue y toma cursos. El más reciente fue de computación y orgullosamente dice que aprobó con nueve; sin embargo, también afirma que ya no practica porque no tiene computadora ni tampoco le encuentra un uso práctico. “Me enseñaron a usar Word, Excel y hasta a mandar un correo, pero dime ¿Qué voy a hacer yo con eso? [...] La verdad sí me ilusionó y hasta tomé el segundo curso, pero yo para qué quiero seguirle”</p>
            <p>Lo mejor que encontró en esos cursos asegura que fueron sus siete amigos, “Los Carrancistas”, como los llama su hermana Chelo haciendo alusión a la rebeldía y alboroto que hacen en todas sus reuniones, doña Inés dice que su hermana considera que salir, celebrar y hacer fiesta por todo son actividades atrevidas y un tanto revolucionarias para su edad. Doña Inés dice que salen al menos una vez al mes y que les encanta buscar pretextos para volverse a ver.</p>
            <p>Compartir y convivir, eso es lo que busca cualquier persona para sentirse acompañada. Así, a pesar de tener casa sola, viven con el corazón contento.</p>
            
            <h2>Corazón roto: otras realidades</h2>
            <p>En México ser una persona adulta mayor es difícil. Esta etapa en el país se correlaciona con el empobrecimiento. Conforme la edad aumenta, los niveles de pobreza también incrementan. Los roles tienden a centrarse dentro del hogar y existen pocas y deficientes oportunidades hacia el exterior. Asimismo, como aseguran Bruno y Acevedo, las condiciones laborales para los adultos mayores tienden a ser malas y los ponen en una situación aún más vulnerable. La mayoría no cuentan con seguridad social por parte de sus empleadores y casi la mitad no tienen prestaciones, por lo que ni su salud, ni su calidad de vida están protegidas.</p>
            <p>En lo que respecta a su autonomía, el documento <a href="http://cedoc.inmujeres.gob.mx/documentos_download/101243_1.pdf">Situación de las personas adultas mayores en México</a> creado por el <strong>Instituto Nacional de las Mujeres</strong>, señala que <strong>“las necesidades de cuidado se incrementan conforme aumenta la edad”</strong>. Es decir, en muchas ocasiones los adultos mayores requieren de terceros para poder gozar de bienestar.</p>
            <p>Sobre esta línea, es importante reconocer el papel fundamental de la familia. Chávez Ortíz explica que es el primer eslabón dentro del círculo social de los adultos mayores. Sin embargo, las dinámicas actuales han propiciado que esto ya no sea posible. Existe una dislocación social de los adultos mayores, donde no sólo se les ignora sino que se les empuja para que salgan del sistema. Eso ha tenido repercusión en la familia, donde al entrar a edades avanzadas las personas pierden su rol funcional en la misma.</p>
            <p>Chávez añade que históricamente a nivel global existe una cultura adultocentrista, donde lo que reina en el sistema es el adulto productivo. Actualmente a nivel económico, político, cultural y social la gente productiva sólo es aquella que tiene cierta edad, porque generan ingresos, mueven el mercado y consumen. Ellos son quienes compran autos, casas y ropa.</p>
            <p>La problemática de productividad entorno a la vejez, explica Ramayo Romero, no sucede sólo en México, sino en toda América Latina y en el mundo en general. </p>
            <p><blockquote>El no ser productivos al llegar a la vejez es una cuestión capitalista, donde la productividad sólo está relacionada con generar dinero; si tú llegas a una edad donde tienes que jubilarte en automático no generas dinero y te vuelves no productivo. Así, el tener o no tener dinero determina tu valor como persona. Entonces, quienes no tienen dinero usualmente son vistos como carga porque alguien más debe mantenerlos. Sin embargo, hay ciertas regiones de México donde aún se rescata la productividad de una manera diferente, donde el adulto mayor tiene un rol que sirve a la comunidad y los vuelve productivos.</blockquote></p>
            <p>Las fallas ocurren también a nivel público, donde pesar de tener programas y realizar esfuerzos en favor de este grupo aún hay fallas graves dentro de las instituciones. Este problema, explica Brito Carranza, está en que el adulto mayor no es visto como persona sino como número y ese número es esencial para tener ciertos beneficios. Al hacer esto se distancian de las necesidades de la persona y se convierten en necesidades de la institución en ‘labor’. Desenfocando todas las prioridades y beneficios del trabajo directo con el adulto mayor.</p>
            <p>Por otro lado, la <strong>falta de sensibilización, de espacios e información sobre y para la vejez</strong> han propiciado que exista discriminación a esta población. Hay un rechazo generalizado hacia las personas de edad y sus necesidades, por lo que es importante comenzar un <strong>cambio estructural de inmediato</strong>.</p>
            <p>Con relación a los daños ocasionados por los estereotipos en la tercera edad, el Inadi de Argentina explica que</p>
            <p><blockquote>Para la población adulta mayor, la consecuencia más grave de los estereotipos negativos es la exclusión de la sociedad, de la comunidad y la vida familiar. La aceptación de los estereotipos por parte de las propias personas mayores puede derivar en que renuncien a buscar ayuda ante problemas médicos que atribuyen a una debilidad propia de la vejez. También puede conducir a no reclamar las prestaciones sociales que les corresponden, debido a que el envejecimiento estereotipado se asimila a retirarse de las relaciones sociales, aceptando el estigma del aislamiento y la pasividad.</blockquote></p>
            <p class="lead">Este mismo documento, señala que los estereotipos más constantes son: falta de independencia, falta de autonomía, son ineficientes, son improductivas, no tienen actividad sexual, siempre tienen enfermedades, tienen trastornos cognitivos, se comportan como niños, buscan la soledad, son rígidos y estructurados, se desvinculan de la sociedad, son resistentes a los cambios, ya no pueden aprender, son menos felices, tienden a deprimirse, presentan características uniformes, se llevan mal con los jóvenes, no realizan actividad física, entre otros. Cultivar un medio de abuso y maltrato hacia los adultos mayores es “resultado de la interacción de una multiplicidad de factores sociales, culturales y psicoemocionales” donde los estereotipos moldean muchos de ellos.</p>
            <p>Es necesario cuestionar qué <strong>estereotipos</strong> delimitan la convivencia con los adultos mayores, porque en ellos están las principales dificultades para ayudarles a tener calidad de vida. Y, en caso de no poder resolver ciertas situaciones bajo medios propios, será pertinente acudir con profesionales. </p>
            <p>El <strong>acompañamiento especializado</strong> debe normalizarse como un elemento de ayuda y beneficio, porque tal como indica la especialista Delgado Morales, puede fungir como un gran apoyo para dar calidad de vida y bienestar al adulto mayor. Esto mismo, debe extenderse no sólo en primera persona sino alrededor: la familia y sus grupos cercanos que son quienes lo van a sostener. Añade que, por ejemplo, el acompañamiento de un terapista ocupacional es, como su nombre lo indica, a través de la ocupación relacionada con las actividades de la vida diaria. De acuerdo a eso se distribuye el tiempo en lo que le gusta hacer al paciente para que se sienta importante y útil; eso eleva su autoestima, lo mantiene activo y hace que su cerebro trabaje de diferentes maneras. </p>
            <p>Es importante reconocer que los especialistas pueden ayudar a <strong>mejorar las dinámicas de convivencia</strong> con los adultos mayores al ofrecer soluciones. Si bien, la familia debe ser el apoyo principal, no tiene que trabajar sola.</p>
            <p>Los adultos mayores deben tener una participación activa, es decir, un rol y ser incluídos en las actividades de toda índole de forma cotidiana. La <strong>OMS</strong> advierte que es importante “la <strong>participación social</strong> en la edad avanzada, la <strong>contribución</strong> que las personas mayores pueden hacer en todos los niveles de la sociedad y el potencial para que esto sea lo normal y no una excepción”. Un factor determinante para que esto sea posible es el entorno, ya que socialmente los adultos mayores son segregados y subestimados; a pesar de tener suficientes capacidades y disposición. </p>
            <p class="lead">Entender a la vejez implica reconocer que si bien, trae retos y dificultades, es una etapa que tiene cientos de posibilidades. Atender las necesidades de esta etapa es un beneficio presente y futuro, pues el bienestar de estas generaciones es la base del bienestar de las futuras; el mundo está envejeciendo y es en primera persona también. Sobre el papel que tiene la familia no hay que olvidar que el niño aprende del grande y la manera en que sean tratados hoy los abuelos será reflejo de cómo serán tratados los padres en el futuro.</p>
        
        </div>

        <div class="col-full s-content__main">
            @include('layouts.chapter-nav')
        </div> <!-- end s-content__main -->

    </article>
</section> <!-- s-content -->

@endsection